version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.12.0.cli-migrations-v3
    ports:
      - "8080:8080"
      - "3030:3030"
      - "9695:9695"
      - "9693:9693"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      #HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      #HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": ""}'
    volumes:
      - ${PWD:-.}/hasura:/hasura
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db_data:
