actions:
  handler_webhook_baseurl: http://localhost:3000
  kind: synchronous
endpoint: http://localhost:8080
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
version: "2"
